version: "3"
services:
  golang:
    build:
      context: "./golang"
      dockerfile: "Dockerfile"
    environment:
      DB_USER: test
      DB_PASS: test
      DB_PATH: postgres
      DB_NAME: qiita
    ports:
      - "9000:9000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - ./golang/.local/share/fish/fish_history:/root/.local/share/fish/fish_history
      - ..:/workspace
      - overwrite:/workspace/.devcontainer/postgres/data
  postgres:
    build:
      context: "./postgres"
      dockerfile: "Dockerfile"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: qiita
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://test:test@postgres:5432/qiita?sslmode=disable
    depends_on:
      - postgres
volumes:
  overwrite:
    driver: 'local'